---
- name: Check source
  stat: path={{ source }}
  register: source_dir

- name: Check target
  stat: path={{ target }}
  register: target_dir

- name: Get source version
  ntdr_get_version.py: path={{ source }}
  register: source_version

- name: Get target version
  ntdr_get_version.py: path={{ target }}
  register: target_version

- name: Fix permission on source
  shell: sudo ntdrchown -a {{ source }}

- name: Fix permission on target
  shell: sudo ntdrchown -a {{ target }}

- name: Sync files
  shell: "rsync -a {{ source }}/sites/default/files/* {{ target }}/sites/default/"

- name: Get souce DB details
  ntdr_get_db_details.py: path={{ source }}/sites/all/drush/{{ source_version.stat.version }}.alias.drushrc.php
  register: source_db_details

- name: Get target DB details
  ntdr_get_db_details.py: path={{ target }}/sites/all/drush/{{ target_version.stat.version }}.alias.drushrc.php
  register: target_db_details

- name: Dump DB from source
  mysql_db: state=dump name={{ source_version.stat.shortver }} target=/var/tmp/{{ source_version.stat.shortver }}.sql login_user={{ source_version.stat.shortver }} login_password={{ source_version.stat.shortver }}

- name: Import DB into target
  mysql_db:
    state: import
    name: "{{ target_version.stat.shortver }}"
    login_user: "{{ target_version.stat.shortver }}"
    login_password: "{{ target_version.stat.shortver }}"
    target: /var/tmp/{{ source_version.stat.shortver }}.sql

- name: Clear caches
  shell: drush -r {{ target }} cc all
