---
- name: Fix local permissions
  shell: sudo ntdrchown -a {{ source }}
  delegate_to: 127.0.0.1

- ntdr_get_version.py: path={{ target }}
  register: target_version

- name: Fix remote permissions
  shell: sudo ntdrchown -a {{ target }}
  when: target_version.stat.found

- stat: path={{ target }}/sites/all/drush/{{ target_version.stat.version }}.alias.drushrc.php
  register: remote_alias

- name: Create alias file
  ntdr_create_drushrc_alias.py: "{{ target }}"
  when: target_version.stat.found and (not remote_alias.stat.exists)

- name: Create sites/all/drush
  file: path={{ source }}/sites/all/drush state=directory mode=0755
  delegate_to: 127.0.0.1

- name: Fetch alias to local site
  fetch: src={{ target }}/sites/all/drush/{{ target_version.stat.version }}.alias.drushrc.php dest={{ source }}/sites/all/drush/ flat=yes
  when: target_version.stat.found

- name: Create change log and patch bump
  ntdr_bump_minor.py: path={{ source }}
  delegate_to: 127.0.0.1

- name: Sync down sites/default/files
  shell: drush -y -r {{ source }} rsync @{{ target_version.stat.version }}:sites/default/files @self:sites/default/ --mode=a
  shell:
  delegate_to: 127.0.0.1

- name: Sync up full file system
  shell: drush -y -r {{ source }} rsync @self @{{ target_version.stat.version }} --mode=a
  delegate_to: 127.0.0.1

- name: Sync DB from local to target
  shell: drush -y sql-sync -r {{ source }} --uri=default @self @{{ target_version.stat.version }} chdir={{ source }}
  delegate_to: 127.0.0.1
  when: with-db is defined

- name: Run up
  shell: drush -y up -r {{ target }} --uri=default chdir={{ target }}

- name: Run updb
  shell: drush -y updb -r {{ target }} --uri=default chdir={{ target }}

- name: Set robots.txt to no follow
  shell: 'echo -e "User-agent: *\nDisallow: /" > {{ target }}/robotx.txt'

- name: Re-fix remote permissions
  shell: sudo ntdrchown {{ target }}

- name: Re-fix local permissions
  shell: sudo ntdrchown {{ source }}
  delegate_to: 127.0.0.1

# - name: Run tests on RC

