---
# Local actions
- name: Fix local permissions
  # TODO Make this a module
  shell: sudo ntdrchown -a {{ source }}
  delegate_to: 127.0.0.1

- name: Get remote version
  ntdr_get_version.py: path={{ target }}
  register: target_version

- name: Fix remote permsissions
  # TODO Make this a module
  shell: sudo ntdrchown -a {{ target }}
  when: target_version.stat.found

- name: Check for remote files
  stat: path={{ target }}/sites/default/files
  register: target_files

- name: Sync down files
  synchronize: src={{ target }}/sites/default/files dest={{ source }}/sites/default mode=pull checksum=yes times=no
  when: target_files.stat.exists

- name: Ensure sites/all/drush
  file: path={{ source }}/sites/all/drush state=directory mode=0755
  delegate_to: 127.0.0.1

- name: Create change log
  # TODO Make this a module
  shell: ntdr_createChangeLog {{ source }} {{ target_version.stat.version }}
  delegate_to: 127.0.0.1

# Remote actions
- name: Full fs sync
  synchronize: src={{ source }} dest={{ target }} checksum=yes times=no

- name: Fix database in settings.php
  lineinfile:
    dest: "{{ target }}/sites/default/settings.php"
    regexp: "database' => "
    line: "      'database' => '{{ target_version.stat.db_ver }}',"
- name: Fix username in settings.php
  lineinfile:
    dest: "{{ target }}/sites/default/settings.php"
    regexp: "username' => "
    line: "      'username' => '{{ target_version.stat.db_ver }}',"
- name: Fix password in settings.php
  lineinfile:
    dest: "{{ target }}/sites/default/settings.php"
    regexp: "password' => "
    line: "      'password' => '{{ target_version.stat.db_ver }}',"

- name: Create new alias for new version
  template: src=alias.drushrc.j2 dest={{ target }}/sites/all/drush/{{ target_version.stat.version }}.alias.drushrc.php

- name: DB Clean
  shell: mysql-dropuser-and-db -u {{ target_version.stat.db_ver }} -m {{ mysql_root_pw }}
  when: with_db is defined

- name: DB Setup
  shell: mysql-create-user-and-db -u {{ target_version.stat.db_ver }} -p {{ target_version.stat.db_ver }} -m {{ mysql_root_pw }}
  when: with_db is defined

- name: Fetch aliases
  synchronize: src={{ target }}/sites/all/drush dest={{ source }}/sites/all mode=pull checksum=yes times=no

- name: Sync up DB
  shell: "drush -y -r {{ source }} --uri=default sql-sync @self @{{ target_version.stat.db_ver }}"
  when: with_db is defined
  delegate_to: 127.0.0.1
