# ansible-playbook \
#   -u trafalgar \
#   --ask-become-pass \
#   -i "192.168.51.11," \
#   --extra-vars="ldap_srv=ldap://192.168.51.4 ldap_pass=FOOBAR ldap_basedn='dc=batch,dc=org,dc=uk' ldap_admin='cn=admin,dc=batch,dc=org,dc=uk'" ldap.yml
---
- hosts: all
  become: true
  roles:
    - { role: ldap }

