---
- hosts: all
  become_method: sudo
  become_user: root
  vars:
    latest: /var/www/latest
    testing: /var/www/testing
  roles:
    - { role: fixpermissions, target: "{{ latest }}" }
    - { role: fixpermissions, target: "{{ testing }}" }
    - passwords
