---
- hosts: all
  vars:
    var_www: /var/www
    sql_file: /tmp/dump.sql
  roles:
      - provision
      # Traget gets defined in the provision script
      - { role: importdb,       target: "{{ target }}" }
      - { role: fixpermissions, target: "{{ target }}" }
      - { role: robots,         target: "{{ target }}", tags: [ 'live' ] }
      - { role: ccall,          target: "{{ target }}" }
