---
# ansible-playbook -i inventory/cottage-servers --limit=wl_new --extra-vars="local_drupal=/home/tobias/workspace/cottaging/sites/wl domain_name=wightlocations.co.uk hostnames=new apache_root=/etc/apache2" provision-cottage.yml
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/provision-server.yml
  roles:
    - provision-server
    - drush
    - provision
    - cottage-apache
    # new_site was declared in provision
    - { role: fixpermissions,  target: "/var/www/{{ new_site }}" }
    - { role: robots-nofollow, target: "/var/www/{{ new_site }}" }
    - { role: ccall,           target: "/var/www/{{ new_site }}" }
