# ansible-playbook -u neontribe --ask-become-pass -i "192.168.21.138," --extra-vars="mysql_root_pw=foobar domain_name=foo.bar.com" provision-server.yml
# add-apt-repository ppa:ondrej/php
# apt-get update
# apt-get install php-uploadprogress
---
- hosts: all
  vars_files:
    - vars/provision_server.yml
  become: true
  roles:
    - { role: provision-server }
