---
- hosts: all
  vars:
    var_www: /var/www
    source: /var/www/latest
    link: /var/www/testing
  roles:
      - { role: dumpdb, target: "{{ source }}" }
      - provision
      # Target gets defined in the provision script
      - { role: importdb,        target: "{{ new_site }}" }
      - { role: fixpermissions,  target: "{{ new_site }}" }
      - { role: robots-nofollow, target: "{{ new_site }}" }
      - { role: ccall,           target: "{{ new_site }}" }
      - { role: swaplinks,       target: "{{ new_site }}" }
