---
# ansible-playbook -i inventory/cottage-servers --limit=wl_live --extra-vars="local=/home/tobias/workspace/cottaging/sites/wl" provision-from-local.yml
- hosts: all
  vars:
    var_www: /var/www
    sql_file: /tmp/dump.sql
    files_bundle: /tmp/files.tgz
  roles:
      - provision
      # Traget gets defined in the provision script
      - { role: importdb,        target: "{{ new_site }}", sql_dump_file: "{{ sql_file }}" }
      - { role: fixpermissions,  target: "{{ new_site }}" }
      - { role: robots-nofollow, target: "{{ new_site }}" }
      - { role: ccall,           target: "{{ new_site }}" }
