---
- hosts: all
  vars:
    var_www: /var/www
    source: /var/www/latest
    link: /var/www/testing
  roles:
      - { role: dumpdb, target: "{{ source }}" }
      - provision
      # Target gets defined in the provision script
      - { role: importdb,        target: "{{ target }}" }
      - { role: fixpermissions,  target: "{{ target }}" }
      - { role: robots-nofollow, target: "{{ target }}" }
      - { role: ccall,           target: "{{ target }}" }
      - { role: changelog,       target: "{{ target }}", bump: minor, from: "{{ source }}" }
      - { role: swaplinks }
