---
- hosts: all
  become_method: sudo
  become_user: root
  vars:
    source: /var/www/latest
    target: /var/www/testing
    patch_release: true
  roles:
    # get real dir of target and register it as tpath
    # check tpath is a drupal + fix permissions on tpath
    - { role: checkisdrupal,  target: "{{ target }}" }
    - { role: fixpermissions, target: "{{ target }}", ownall: 'yes' }

    # Sync files
    - { role: syncfiles, source: "{{ source }}", target: "{{ target }}" }

    # DB - Import the live DB
    - { role: dumpdb,    target: "{{ source }}" }
    - { role: importdb,  target: "{{ target }}" }

    # MODULE & THEME
    # Rsync sites/all (exclude .git, delete missing)
    - { role: pushfiles, source: "{{ local }}/sites/all", target: "{{ target }}/sites", deletemissing: 'yes' }

    # Always
    # Fix permissions
    - { role: fixpermissions, target: "{{ target }}" }
    - { role: set-read-only,  target: "{{ target }}", rw: "yes" }
    - { role: updb,           target: "{{ target }}" }
    - { role: robots,         target: "{{ target }}", tags: [ 'nofollow' ] }
    - { role: ccall,          target: "{{ target }}" }
    # Role up changelog minor
    - { role: changelog, bump: 'patch' }
