---
- hosts: all
  become_method: sudo
  become_user: root
  vars:
    target: /var/www/testing
    patch_release: true
  roles:
    # check the source is a drupal
    # fix permissions on source

    # get real dir of target and register it as tpath
    # check tpath is a drupal
    # fix permissions on tpath

    # FILES
    # Rsync files when files tag is set

    # DB - when db tag is set
    # back up remote db
    # dump local db
    # import db

    # MODULE & THEME - when modules flag is set
    # Checkout modules to match latest tags
    # Rsync sites/all (exclude .git)
