---
- hosts: all
  vars:
    target: /var/www/testing
    patch_release: true
  vars_prompt:
    - name: mysql_root_pw
      prompt: "Enter mysql root password for the remote mysql server"
      private: true
      when: mysql_root_pw is not defined
  roles:
    - push
