---
- hosts: all
  vars:
    target: /var/www/testing
  vars_prompt:
    - name: mysql_root_pw
      prompt: "Enter mysql root password for the local mysql server"
      private: true
      when: mysql_root_pw is not defined
  roles:
    - push-local-to-remote
