---
- hosts: all
  vars:
    source: /var/www/latest
    target: /var/www/testing
  roles:
      - { role: checkisdrupal,  target: "{{ source }}" }
      - { role: checkisdrupal }
      - { role: dumpdb,         target: "{{ source }}" }
      - { role: importdb }
      - { role: fixpermissions, target: "{{ source }}" }
      - { role: fixpermissions }
      - { role: syncfiles }
      - { role: updb }
      - { role: robots, tags: [ 'fulllive' ] }
      - { role: ccall }
      - { role: smoketest }
      - { role: swaplinks, link: "{{ source }}", clear: "{{ target }}" }
