---
- hosts: all
  vars:
    source: /var/www/latest
    target: /var/www/testing
  roles:
      - { role: checkisdrupal,  target: "{{ source }}" }
      - { role: checkisdrupal }
      - { role: dumpdb,         target: "{{ source }}" }
      - { role: importdb }
      - { role: fixpermissions, target: "{{ source }}" }
      - { role: fixpermissions }
      - { role: syncfiles }
      - { role: updb }
      - { role: robots, tags: [ 'live' ] }
      - { role: ccall }
      - { role: smoketest }
      - { role: swaplinks, link: /var/www/latest }
      #
      # THESE ARE NOW HANDLED BY: provision-from-remote.yml
      #
      #- { role: newdrupal,      from:   "{{ target }}", bump: minor }
      #- { role: importdb,       target: "{{ newdrupal }}" }
      #- { role: fixpermissions, target: "{{ newdrupal }}" }
      #- { role: syncfiles,      source: "{{ target }}", target: "{{ newdrupal }}" }
      #- { role: syncmodules,    source: "{{ target }}", target: "{{ newdrupal }}" }
      #- { role: syncthemes,     source: "{{ target }}", target: "{{ newdrupal }}" }
      #- { role: synchtaccess,   source: "{{ target }}", target: "{{ newdrupal }}" }
      #- { role: changelog,      target: "{{ newdrupal }}", bump: minor, from: "{{ source }}" }
      #- { role: updb,           target: "{{ newdrupal }}" }
      #- { role: robots,         target: "{{ newdrupal }}", tags: [ 'nofollow' ] }
      #- { role: ccall,          target: "{{ newdrupal }}" }
      #- { role: smoketest,      target: "{{ newdrupal }}" }
      #- { role: swaplinks,      target: "{{ newdrupal }}", link: /var/www/testing }
