---
- name: Sync files onto remote site
  synchronize:
    src: "{{ source }}"
    dest: "{{ destination }}"
    rsync_opts:
      - "-rlD"
      - "--log-file=/tmp/sync.log"
      - "--exclude='files/tabs-imagecache'"
      - "--exclude='.git'"
      - "--exclude='.sass-cache'"
  when: deletemissing is undefined

- name: Sync files onto remote site and delete old files
  synchronize:
    src: "{{ source }}"
    dest: "{{ destination }}"
    delete: yes
    rsync_opts:
      - "-rlD"
      - "--log-file=/tmp/sync.log"
      - "--exclude='files/tabs-imagecache'"
      - "--exclude='.git'"
      - "--exclude='.sass-cache'"
  when: deletemissing is defined
