---
- name: Sync files folder
# This seems to take a VERY long time
#  synchronize:
#    src: "{{ source }}/sites/default/files"
#    dest: "{{ target }}/sites/default/"
#    rsync_opts:
#      - "-rlD"
#  delegate_to: "{{ inventory_hostname }}"
  shell: rsync -rlD --exclude='files/tabs-imagecache' --progress --log-file=/tmp/sync.log {{ source }}/sites/default/files {{ target }}/sites/default/
  become: yes
