---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: Template up the debconf data
  template: src=debconf-set-selections.j2 dest=/tmp/debconf-set-selections

- name: Set mysql-server/root_password
  shell: "debconf-set-selections /tmp/debconf-set-selections"

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items: victory.packages

- file: src=dnsmasq.conf dest=/etc/dnsmasq.conf
- service: name=dnsmasq enabled=yes

- template: src=hosts.j2 dest=/etc/hosts
- template: src=hostname.j2 dest=/etc/hostname

- service: name=slapd enabled=yes
- service: name=slapd state=started
- copy: content={{ ldap_users }} dest=/tmp/users.ldif
  - shell: ldapadd -x -w {{ ldap_pass }} -H ldapi:/// -D '{{ ldap_admin }}' -f /tmp/users.ldif
