---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: Template up the debconf data
  template: src=debconf-set-selections.j2 dest=/tmp/debconf-set-selections

- name: Set mysql-server/root_password
  shell: "debconf-set-selections /tmp/debconf-set-selections"

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items: victory.packages

- file: src=dnsmasq.conf dest=/etc/dnsmasq.conf
- service: name=dnsmasq enabled=yes

- template: src=hosts.j2 dest=/etc/hosts
- template: src=hostname.j2 dest=/etc/hostname

- service: name=slapd state=started
- copy: src=directory.ldif dest=/tmp/directory.ldif
  # The ldif for this is harvested with slapcat > /tmp/directory.ldif
  # And the first two objects have been removed
- shell: ldapmodify -c -x -w {{ ldap_pass }} -D "cn=admin,dc=batch,dc=org,dc=uk" -a -f /tmp/directory.ldif
- file: path=/tmp/directory.ldif state=absent
- service: name=slapd enabled=yes








