---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: Template up the debconf data
  template: src=debconf-set-selections.j2 dest=/tmp/debconf-set-selections

- name: Set mysql-server/root_password
  shell: "debconf-set-selections /tmp/debconf-set-selections"

- name: Create users ldiff file
  copy: content={{ ldap_users }} dest=/tmp/users.ldif

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items: victory.packages

- name: Set /etc/dnsmasq.conf
  file: src=dnsmasq.conf dest=/etc/dnsmasq.conf

- name: Ensure dnsmasq is enabled
  service: name=dnsmasq enabled=yes

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: Set hostname
  template: src=hostname.j2 dest=/etc/hostname

- name: Ensure slapd is enabled
  service: name=slapd enabled=yes

- name: Ensure slapd is started
  service: name=slapd state=started

- name: Insert users into LDAP
  shell: ldapadd -x -w {{ ldap_pass }} -H ldapi:/// -D '{{ ldap_admin }}' -f /tmp/users.ldif
