---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: Template up the debconf data
  template: src=debconf-set-selections.j2 dest=/tmp/debconf-set-selections

- name: Set mysql-server/root_password
  shell: "debconf-set-selections /tmp/debconf-set-selections"

- name: Create users ldiff file
  copy: content={{ ldap_users }} dest=/tmp/users.ldif

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items: victory.packages

- name: Set /etc/dnsmasq.conf
  file: src=dnsmasq.conf dest=/etc/dnsmasq.conf

- name: Ensure dnsmasq is enabled
  service: name=dnsmasq enabled=yes

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: Set hostname
  template: src=hostname.j2 dest=/etc/hostname

- name: Ensure slapd is enabled
  service: name=slapd enabled=yes

- name: Ensure slapd is started
  service: name=slapd state=started

- name: Insert users into LDAP
  # shell: ldapadd -x -w {{ ldap_pass }} -H ldapi:/// -D '{{ ldap_admin }}' -f /tmp/users.ldif
  shell: ldapmodify -c -a -H ldapi:/// -D '{{ ldap_admin }}' -w {{ ldap_pass }} -f /tmp/users.ldif
  # This is not ideal but it allow the import to be run on an already populated ldap
  ignore_errors: yes

###########################################################
# This whole chunk needs ansible 2.1 at least to upload and decrypt the easy rsa keys
#- name: Make easy rsa dir
#  file:
#    path: /etc/openvpn/easy-rsa
#    state: directory
#
#- name: Upload easy RSA files for VPN
#  copy: src=easyrsa.tgz dest=/tmp/easyrsa.tgz
#
# Use this until 2.2 when we can use the "remote_src: yes" becomes available
#- name: Unpack easy rsa files
#  shell: tar zxf /tmp/easyrsa.tgz
#  args:
#     chdir: /etc/openvpn/easy-rsa

#- name: Unpack easy rsa files
#  unarchive:
#    src: easyrsa.tgz
#    dest: /etc/openvpn/easy-rsa
#    remote_src: yes
#######################################################

# Calibre server
# Transmission
# Motion

# DNS Masq
# Automounter + links to 192.168.51.5
# Apache confs, camera.conf media.conf transmission.conf media.conf
