---
- name: Turn off root login via ssh
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no"

- name: Update TCP Keep Alive for SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp=^TCPKeepAlive line="TCPKeepAlive yes"
