---
- name: Update apt
  become: true
  apt: update_cache=yes cache_valid_time=3600

- user:
  name: "{{ user }}"
  password: "{{password}}"
  shell: /bin/bash
  groups: adm,sudo,www-data,crontab,syslog,admin
  append: yes

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ user }} ALL = (ALL) NOPASSWD: /opt/shell-tools/ntresetperms,/opt/shell-tools/ntdrchown'
    validate: visudo -cf %s
