## Collect data
# Source dir
- stat: path={{ source }}
  register: source_dir

# Source version
- name: Get source version
  ntdr_get_version.py: path={{ source }}
  register: source_version

- name: Source db
  ntdr_get_db_details.py: path={{ source }}/sites/all/drush/{{ source_version.stat.version }}.alias.drushrc.php
  register: source_db_details

# Target dir
- name: Ensure target dir
  file: path={{ target }} state=directory mode=0755

- stat: path={{ target }}
  register: target_dir

# Target db
- name: Create minor bump - short version
  shell: "echo {{ source_version.stat.brand }}_{{ source_version.stat.major }}_$(({{ source_version.stat.minor }} + 1))" 
  register: target_short_version

- name: Create minor bump - long version
  shell: "echo {{ source_version.stat.brand }}_{{ source_version.stat.major }}_$(({{ source_version.stat.minor }} + 1))_{{ source_version.stat.patch }}" 
  register: target_long_version

# Fix source permissions
- name: Fix source permsissions
  shell: sudo ntdrchown -a {{ source }}

# Fix target permissions
- name: Fix target permsissions
  shell: sudo ntdrchown -a {{ target }}
  ignore_errors: yes

# Sync files
- name: Sync files
# synchronize: src={{ source }}/* dest={{ target }} mode=pull checksum=yes times=no
  shell: "rsync -a {{ source }}/* {{ target }}"
  delegate_to: "{{inventory_hostname}}"

# Create change log
- name: Create change log
  shell: ntdr_createChangeLog {{ target }} {{ target_long_version.stdout }}

# Ensure DB
- name: Ensure target DB
  mysql_db: name={{ target_short_version.stdout }} state=present login_user=root login_password={{ mysql_root_pw }}
  tags: db

# Ensure DB user
- name: Ensure target DB user
  mysql_user: name={{ target_short_version.stdout }} password={{ target_short_version.stdout }} priv={{ target_short_version.stdout }}.*:ALL state=present login_user=root login_password={{ mysql_root_pw }}
  tags: db

# Dump source db
- name: Dump source DB
  mysql_db: state=dump name={{ source_version.stat.shortver }} target=/var/tmp/{{ source_version.stat.shortver }}.sql login_user=root login_password={{ mysql_root_pw }}

# Import source DB into target DB
- name: Import source DB
  mysql_db:
    state: import
    name: "{{ target_short_version.stdout }}"
    login_user: "{{ target_short_version.stdout }}"
    login_password: "{{ target_short_version.stdout }}"
    target: /var/tmp/{{ source_version.stat.shortver }}.sql

- name: Fix database in settings.php
  lineinfile:
    dest: "{{ target }}/sites/default/settings.php"
    regexp: "database' => "
    line: "      'database' => '{{ target_short_version.stdout }}',"
- name: Fix username in settings.php
  lineinfile:
    dest: "{{ target }}/sites/default/settings.php"
    regexp: "username' => "
    line: "      'username' => '{{ target_short_version.stdout }}',"
- name: Fix password in settings.php
  lineinfile:
    dest: "{{ target }}/sites/default/settings.php"
    regexp: "password' => "
    line: "      'password' => '{{ target_short_version.stdout }}',"

- name: Create new alias for new version
  # template: src=alias.drushrc.j2 dest={{ target }}/sites/all/drush/{{ target_version.stat.version }}.alias.drushrc.php
  ntdr_create_drushrc_alias.py:
    path: "{{ target }}"
    name: "{{ target_long_version.stdout }}"
    dbver: "{{ target_short_version.stdout }}"
    user: "{{ ansible_ssh_user }}"
    host: "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"


