---
- name: Clean out local taget repo
  file: path="{{ tmp }}/{{ repo }}" state=absent

- name: Clean out local ntdr-pas repo
  file: path="{{ tmp }}/ntdr-pas" state=absent

- name: Checkout the target repo
  git: repo=ssh://git@bitbucket.org/neontabs/{{ repo }}.git dest={{ tmp }}/{{ repo }} update=yes version=master force=yes accept_hostkey=yes

- name: Checkout ntdr-pas repo
  git: repo=ssh://git@github.com/neontribe/ntdr-pas.git dest={{ tmp }}/ntdr-pas update=yes version=master force=yes accept_hostkey=yes

- debug: msg="{{ tmp }}/{{ repo }}/changelog.json"

- name: Tag repo with message
  shell: git tag {{ newtag }} -m "[{{ ansible_date_time.iso8601 }}] {{ tagmessage }}"
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Generate new changelog
  shell: "drush ntc {{ tmp }}/{{ repo }} > {{ tmp }}/{{ repo }}/changelog.json"

- name: Add change log
  shell: git add -A
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Commit change log
  shell: git commit -a -m "Updated changelog"
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Push changelog and tag
  shell: git push origin master --tags
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Update makefile and push makefile
  update_makefiles: brandcodes={{ brandcodes }} tag={{ newtag }} ntdrpas={{ tmp }}/ntdr-pas repo={{ repo }}
  register: update

- debug: var=update

- name: Commit make files
  shell: git commit -a -m "Updated make files for {{ brandcodes }} - {{ newtag }}, {{ tagmessage }}"
  args:
    chdir: "{{ tmp }}/ntdr-pas"
  when: pretend is not defined

- name: Push make files
  shell: git push origin master
  args:
    chdir: "{{ tmp }}/ntdr-pas"
  when: pretend is not defined
