

- name: Checkout the target repo
  git: repo=ssh://git@bitbucket.org/neontabs/{{ repo }}.git dest={{ tmp }}/{{ repo }} update=yes version=master

- name: Checkout the target repo
  git: repo=ssh://git@github.com:neontribe/ntdr-pas.git dest={{ tmp }}/ntdr-pas update=yes version=master

- name: Bump version, update change log and push changelog
  bumpup: repo={{ tmp }}/{{ repo }} bump={{ bump }}
  register: bumped

- debug: var=bumped

- name: Update makefile and push makefile
  update_makefiles: brandcodes={{ brandcodes }} repo={{ repo }} tag={{ bumped.stat.new_tag }} ntdrpas={{ tmp }}/ntdr-pas
