---
- name: Clean out local taget repo
  file: path="{{ tmp }}/{{ repo }}" state=absent

- name: Clean out local ntdr-pas repo
  file: path="{{ tmp }}/ntdr-pas" state=absent

- name: Checkout the target repo
  git: repo=ssh://git@bitbucket.org/neontabs/{{ repo }}.git dest={{ tmp }}/{{ repo }} update=yes version=master force=yes accept_hostkey=yes

- name: Checkout ntdr-pas repo
  git: repo=ssh://git@github.com/neontribe/ntdr-pas.git dest={{ tmp }}/ntdr-pas update=yes version=master force=yes accept_hostkey=yes

- name: Get last log message
  shell: git log -1 --pretty="%h|%B"
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  register: last_log

- debug: var=last_log

- name: Get git logs
  shell: "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit > changelog.raw"
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  register: tag_log

- name: Create changelog
  shell: "ansi2html.sh < changelog.raw > changelog.html"
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  register: changelog

- debug: var=changelog

- name: Add change log
  shell: git add -A
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Commit change log
  shell: git commit -a -m "Updated changelog"
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Tag repo with message
  shell: git tag {{ newtag }} -m "{{ tagmessage }}"
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Push changelog and tag
  shell: git push origin master --tags
  args:
    chdir: "{{ tmp }}/{{ repo }}"
  when: pretend is not defined

- name: Update makefile and push makefile
  update_makefiles: brandcodes={{ brandcodes }} tag={{ newtag }} ntdrpas={{ tmp }}/ntdr-pas repo={{ repo }}
  register: update

- debug: var=update

- name: Commit make files
  shell: git commit -a -m "Updated make files for {{ brandcodes }}"
  args:
    chdir: "{{ tmp }}/ntdr-pas"
  when: pretend is not defined

- name: Push make files
  shell: git push origin master
  args:
    chdir: "{{ tmp }}/ntdr-pas"
  when: pretend is not defined
