---
- debug: var=repo

- name: Checkout the target repo
  git: repo=ssh://git@bitbucket.org/neontabs/{{ repo }}.git dest={{ tmp }}/{{ repo }} update=yes version=master
  # git: repo=git://git@bitbucket.org:neontabs/{{ repo }}.git dest={{ tmp }}/{{ repo }} update=yes version=master

- name: Bump version, update change log and push changelog
  bumpup: repo={{ tmp }}/{{ repo }} bump={{ bump }}
  register: bump

- name: Update makefile and push makefile
  update_makefiles: brandcodes={{ brandcodes }} repo={{ repo }} tag={{ bump.stat.new_tag }} ntdrpas={{ ntdrpas }}
