---
- name: Update apt
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Template up the debconf data
  become: true
  template: src=debconf-set-selections.j2 dest=/tmp/debconf-set-selections

- name: Set mysql-server/root_password
  become: true
  shell: "debconf-set-selections /tmp/debconf-set-selections"

- name: Remove debconf file
  become: true
  file: path=/tmp/debconf-set-selections state=absent

- name: Configure the timezone
  become: true
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: true
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  become: true
  shell: locale-gen {{server.locale}}

- name: Install System Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items: server.packages

- name: Set vim as default editor
  become: true
  alternatives: name=editor path=/usr/bin/vim.basic

- name: Enable PHP 7
  become: true
  apache2_module: name=rewrite state=present

- name: Enable SSL mod
  become: true
  apache2_module: name=ssl state=present

- name: Enable SSL site
  become: true
  file: src=/etc/apache2/sites-available/default-ssl.conf dest=/etc/apache2/sites-enabled/default-ssl.conf state=link

- name: Enable rewrite
  become: true
  apache2_module: name=php7.0 state=present
  notify: restart apache2

- name: Clone shell tools
  become: true
  git:
    repo: "https://github.com/tobybatch/Shell-tools.git"
    dest: "/opt/shell-tools"
    version: master
    update: yes
    force: yes
    accept_hostkey: yes
  tags: sheltools

- name: Adding shell tools to the path
  copy:
    content: PATH=$PATH:/opt/shell-tools/
    dest: /etc/profile.d/shell-tools.sh
  #  lineinfile:
  #  dest: /etc/environment
  #  line: 'export PATH=$PATH:/opt/shell-tools/'
  #  insertafter: 'EOF'
  #  regexp: 'export PATH=\$PATH:/opt/shell-tools/'
  #  state: present
  tags: sheltools
