---
- name: Update apt
  become: ture
  apt: update_cache=yes cache_valid_time=3600

- name: Template up the debconf data
  become: ture
  template: src=debconf-set-selections.j2 dest=/tmp/debconf-set-selections

- name: Set mysql-server/root_password
  become: ture
  shell: "debconf-set-selections /tmp/debconf-set-selections"

- name: Remove debconf file
  become: ture
  file: path=/tmp/debconf-set-selections state=absent

- name: Configure the timezone
  become: ture
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: ture
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  become: ture
  shell: locale-gen {{server.locale}}

- name: Install System Packages
  become: ture
  apt: pkg={{ item }} state=latest
  with_items: server.packages

- name: Set vim as default editor
  become: ture
  alternatives: name=editor path=/usr/bin/vim.basic

- name: Enable PHP 7
  become: ture
  apache2_module: name=rewrite state=present

- name: Enable SSL mod
  become: ture
  apache2_module: name=ssl state=present

- name: Enable SSL site
  become: ture
  file:src=/etc/apache2/sites-available/default-ssl.conf dest=/etc/apache2/sites-enabled/default-ssl.conf state=link

- name: Enable rewrite
  become: ture
  apache2_module: name=php7.0 state=present
  notify: restart apache2
