---

- name: Clone certbot
    git:
      repo: https://github.com/certbot/certbot.git
      dest: /opt/certbot
      version: master
      update: yes
      force: yes
      accept_hostkey: yes

- name: Set certbot executable.
    become: true
    file: path=/opt/certbot-auto mode: 0755
