---
- name: "Stat from directory {{ from }}"
  stat: path="{{ from }}"
  register: from_folder
  when: from is defined

- name: "if {{ from_folder }} is a link get it's real path"
  set_fact: from_real_folder={{ from_folder.stat.lnk_source }}
  when: from is defined and from_folder.stat.islnk is defined and from_folder.stat.islnk

- name: "if {{ from_folder }} is a real folder register the directory"
  set_fact: from_real_folder={{ from }}
  when: from is defined and from_folder.stat.isdir

- name: Create changelog src file
  file: path="{{ from_real_folder }}/changelog.json" state=touch

- name: Register changelog sourec file
  set_fact: changelog={{ from_real_folder }}/changelog.json
  when: from_real_folder is defined

- name: Import change log
  shell: cp {{ changelog }} {{ target }}/changelog.json
  when: changelog is defined

- name: Update changelog for child modules
  shell: drush -r {{ target }} --uri=default ntrc {{ bump }}
  # For now ignore errors, once modules have been pushed this won't be needed.
  ignore_errors: yes

