---
- debug: var=target

- name: Backup existing robots.txt
  shell: 'cp {{ target }}/robots.txt {{ target }}/robots.`date +"%Y%m%d"`.txt'
  tags: always

- name: Install nofollow robots.txt
  copy: src=robots.nofollow.txt dest={{ target }}/robots.txt
