---
- name: Sync down latest sites/default/files
  shell: drush -y -r {{ local }} rsync @{{ source_version.stat.version }}:%files/ @self:%files --include-conf --include-vcs --progress --mode=a
  delegate_to: 127.0.0.1
