---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items: calibreserver.packages

- name: Get bleeding edge package
  get_url:
    url: 'https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py'
    dest: /tmp/linux-installer.py
    mode: 0644

- name: Install calibre server
  shell: python /tmp/linux-installer.py

- name: Create calibre-library
  file: path=/var/calibre-library state=directory

- name: calibre-library/toadd
  file: path=/var/calibre-library/toadd state=directory

- name: Copy the books off the NAS
  copy:
    src: "{{ item }}"
    dest: /var/calibre-library/toadd
    mode: 664
  with_fileglob:
    - /net/192.168.51.5/mnt/HD/HD_a2/public/books/to-add/*

