---

- hosts: all
  vars:
    source: /var/www/latest
  vars_prompt:
    - name: mysql_root_pw
      prompt: "Enter mysql root password for the remote mysql server"
      private: true
      when: mysql_root_pw is not defined
  roles:
    - minor-release
