---
- name: Install readonly module
  shell: "drush -r {{ target }} --uri=default en -y readonlymode"

- name: Turn readonly on
  shell: "drush -r {{ target }} --uri=default vset site_readonly 1"

- name: Dump DB from {{ target }}
  shell: drush -r {{ target }} sql-dump --ordered-dump --structure-tables-key=common --result-file=/tmp/source.sql

- name: Restore read write
  shell: "drush -r {{ target }} --uri=default vset site_readonly 0"
